name: release_nightly

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'

on:
  workflow_dispatch:
  push:
    tags:
      - nightly
  schedule:
    - cron: '0 7 * * *'

jobs:
  build_linux:
    if: github.repository_owner == 'abdoulayecoumbassa74-design'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: rust-lang/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build release
        run: cargo build --release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # C'est ici le changement !
        with:
          name: brother-ide-ai-linux
          path: target/release/
          retention-days: 7

  build_windows:
    if: github.repository_owner == 'abdoulayecoumbassa74-design'
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: rust-lang/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build release
        run: cargo build --release
        shell: pwsh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # C'est ici aussi !
        with:
          name: brother-ide-ai-windows
          path: target/release/
          retention-days: 7

